version: '3'

services:
  web:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 my_calendar_app.wsgi:application
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_database_name  # ;)
      POSTGRES_USER: your_database_user  # ;)
      POSTGRES_PASSWORD: your_database_password  # ;)
  redis:
    image: "redis:alpine"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"

volumes:
  postgres_data:
